Set meshtastic service working directory to data dir
nvmd/nixos-meshtastic pull request #2
Opened 2024-12-23 20:36 UTC by srd424

Self-signed certs for HTTPS seem to get saved in whatever meshtasticd's current working directory is, so setting that to the configured data directory seems reasonable?

2024-12-23 21:39 UTC, nvmd requested changes
Just one little change for the sake of keeping the code cleaner

2024-12-23 21:39 UTC, nvmd commented on modules/meshtastic.nix
> +          WorkingDirectory = "${cfg.dataDir}";
Plain `cfg.dataDir` should be enough

2024-12-23 21:40 UTC, nvmd commented
Hi @srd424, thank you for your PR!
Yes, I think that makes perfect sense. Could you please just make one more minor change in the commit?

2024-12-23 21:42 UTC, srd424 commented
Yup, no worries - will sort tomorrow, festivities permitting!

2024-12-23 21:54 UTC, nvmd commented
Sure, have a lovely holiday!

2025-01-01 15:18 UTC, srd424 commented
Sorry for delay, finally got around to tweaking this!

2025-01-02 12:31 UTC, nvmd approved these changes

2025-01-02 12:32 UTC, merged

2025-01-02 12:32 UTC, nvmd commented
No worries. Thank you!